### ISSUE TITLE
编译app.js/app.css缓存问题

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa-build#19]
每次跑nowa build，编译出来的其他文件都会根据文件大小hash进行重命名，基本不会有缓存问题，但是app.js和app.css命名不变，路径不变，每次都会有缓存，有没有什么好办法

**Comment by gbk** [comment]
加时间戳怎么样？
/app.js?t=1428123817641

**Comment by WangYang-Rex** [comment]
现在正是这么做的
