### ISSUE TITLE
@keyframes 命名压缩可能导致命名冲突以及影响 <a> 元素样式

### ISSUE THREAD

**Issue by yukap6** [nowa-webpack/nowa-build#25]
- 多个文件的 @keyframes 会有可能造成命名冲突

less 代码压缩前
`
@keyframes name-for-keyframes{
  background-color: #f60;
}
`

压缩后
`
@keyframes a{
  background-color: #f60;
}
`

- 影响到了 a 元素样式

chrome 版本：Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by gbk** [comment]
https://github.com/ben-eb/cssnano/issues/247
