### ISSUE TITLE
在webpack.config.js中新增了一个plugins，发现执行了两次

### ISSUE THREAD

**Issue by WisestCoder** [nowa-webpack/nowa-build#28]
输出compilers，发现compilers里面带了两份一模一样的webpack配置，貌似是进了multi-compilers，想问一下什么条件下会进multi-compilers，项目是多页面、无路由、无redux、无refast的uxcore项目

**Comment by WisestCoder** [comment]
刚看了源码，发现是abc.json中配置了buildvars，从而输出不同后缀的代码，那么如果我写的插件只想执行一次，该怎么处理

**Comment by gbk** [comment]
@WisestCoder 变量的候选值只有一个的话，就不会进 multi-compiler 了
